In [38]:
from tensorflow.keras.preprocessing.text import one_hot

In [39]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'i am a good developer',
        'Understand the meaning of words'
        ,'nlp is an interesting topic'
        ,'why is nigga the best word']

In [40]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'i am a good developer',
 'Understand the meaning of words',
 'nlp is an interesting topic',
 'why is nigga the best word']

In [41]:
voc_size = 10000

In [42]:
one_hot_repr = [one_hot(word,voc_size)for word in sent]

In [43]:
one_hot_repr

[[4248, 1298, 1534, 4254],
 [4248, 1298, 1534, 7527],
 [4248, 1264, 1534, 1775],
 [4862, 4916, 8943, 1809, 4627],
 [4862, 4916, 8943, 1809, 9098],
 [944, 4248, 2931, 1534, 9536],
 [6447, 3381, 9689, 833, 649],
 [2020, 3381, 5894, 4248, 3786, 9729]]

In [44]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
import numpy as np


In [45]:
sent_length = 8


In [46]:
embedded_docs = pad_sequences(one_hot_repr, padding="pre",maxlen=sent_length)

In [47]:
embedded_docs

array([[   0,    0,    0,    0, 4248, 1298, 1534, 4254],
       [   0,    0,    0,    0, 4248, 1298, 1534, 7527],
       [   0,    0,    0,    0, 4248, 1264, 1534, 1775],
       [   0,    0,    0, 4862, 4916, 8943, 1809, 4627],
       [   0,    0,    0, 4862, 4916, 8943, 1809, 9098],
       [   0,    0,    0,  944, 4248, 2931, 1534, 9536],
       [   0,    0,    0, 6447, 3381, 9689,  833,  649],
       [   0,    0, 2020, 3381, 5894, 4248, 3786, 9729]], dtype=int32)

In [48]:
dim = 10

In [49]:
from tensorflow.keras.models import Sequential

In [50]:
from tensorflow.keras.layers import Input

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


array([[[ 0.02401043,  0.01044273, -0.01013666, -0.04210659,
         -0.01350863,  0.00341859, -0.01963   ,  0.0060364 ,
         -0.04710114, -0.00540093],
        [ 0.02401043,  0.01044273, -0.01013666, -0.04210659,
         -0.01350863,  0.00341859, -0.01963   ,  0.0060364 ,
         -0.04710114, -0.00540093],
        [ 0.02401043,  0.01044273, -0.01013666, -0.04210659,
         -0.01350863,  0.00341859, -0.01963   ,  0.0060364 ,
         -0.04710114, -0.00540093],
        [ 0.02401043,  0.01044273, -0.01013666, -0.04210659,
         -0.01350863,  0.00341859, -0.01963   ,  0.0060364 ,
         -0.04710114, -0.00540093],
        [-0.00218973, -0.00366435,  0.01715288,  0.01741387,
         -0.0229467 ,  0.02426239,  0.03243193, -0.01924127,
         -0.0291883 ,  0.04558189],
        [ 0.0345437 , -0.04039291,  0.01211699,  0.03430164,
          0.03621291, -0.03128569, -0.02928004, -0.0033292 ,
         -0.0208374 ,  0.02864018],
        [-0.01106906,  0.02511835,  0.02806956,  0.0

In [54]:
embedded_docs[0]

array([   0,    0,    0,    0, 4248, 1298, 1534, 4254], dtype=int32)